# Generated by Django 5.2 on 2025-04-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_linking_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
