# Generated by Django 5.0.4 on 2024-05-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_linking_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='for_which_model',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='for_which_model',
        ),
    ]
