# Generated by Django 4.2.13 on 2024-05-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_linking_models', '0006_alter_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='content_type_linking_models.attachment'),
        ),
    ]
