# Generated by Django 5.1.7 on 2025-03-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('stock', '0002_remove_stocklocationtype_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.purchaseorder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem')),
            ],
        ),
    ]
