# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('company', '0002_initial'),
        ('inventory', '0003_initial'),
        ('orders', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='customer',
            field=models.ForeignKey(help_text='Company from which items are being returned', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.company', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='order_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_sales', to=settings.AUTH_USER_MODEL, verbose_name='shipped by'),
        ),
        migrations.AddField(
            model_name='salesordershipment',
            name='checked_by',
            field=models.ForeignKey(blank=True, help_text='User who checked this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Checked By'),
        ),
        migrations.AddField(
            model_name='salesordershipment',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='salesordershipment',
            name='order',
            field=models.ForeignKey(help_text='Sales Order', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orders.salesorder', verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='salesordershipment',
            unique_together={('order', 'reference')},
        ),
    ]
