# Generated by Django 5.1.7 on 2025-03-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchaseorderlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='target_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
    ]
