# Generated by Django 5.2 on 2025-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseorderlineitem_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate as a percentage (e.g. 5.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate as a percentage (e.g. 5.0)', max_digits=5),
        ),
    ]
