# Generated by Django 5.2 on 2025-04-06 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_purchaseorderlineitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordershipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesordershipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
