# Generated by Django 4.2.13 on 2024-06-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_sub_region_companyaddress_subregion'),
        ('orders', '0004_alter_purchaseorder_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
    ]
