# Generated by Django 5.2 on 2025-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_salesordershipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('issued', 'Isshued'), ('completed', 'Complete'), ('cancelled', 'Cancelled'), ('lost', 'Lost'), ('returned', 'Returned')], default='pending', help_text='Purchase order status', max_length=20, verbose_name='Status'),
        ),
    ]
