# Generated by Django 5.2 on 2025-04-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('issued', 'Isshued'), ('completed', 'Complete'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('lost', 'Lost'), ('returned', 'Returned')], default='pending', help_text='Purchase order status', max_length=20, verbose_name='Status'),
        ),
    ]
