# Generated by Django 5.2 on 2025-04-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
