# Generated by Django 5.2 on 2025-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_purchaseorderlineitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
