# Generated by Django 5.2 on 2025-04-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_staffroleassignment_role'),
        ('orders', '0009_purchaseorderlineitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='inventory',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
    ]
