# Generated by Django 5.2 on 2025-04-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_staffroleassignment_role'),
        ('orders', '0010_remove_purchaseorder_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
    ]
