# Generated by Django 5.2 on 2025-04-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_staffroleassignment_role'),
        ('orders', '0011_alter_purchaseorder_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='complete_date',
            field=models.DateTimeField(blank=True, help_text='Date order was completed', null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('issued', 'Isshued'), ('completed', 'Complete'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('received', 'Received'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('lost', 'Lost'), ('returned', 'Returned')], default='pending', help_text='Purchase order status', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='complete_date',
            field=models.DateTimeField(blank=True, help_text='Date order was completed', null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.companyprofile'),
        ),
    ]
