# Generated by Django 5.2 on 2025-04-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_purchaseorder_received_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
    ]
