# Generated by Django 5.2 on 2025-04-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='return_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for the return', null=True, verbose_name='Return Reason'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='complete_date',
            field=models.DateTimeField(blank=True, help_text='Date order was completed', null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(blank=True, help_text='Date order was issued', null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='issue_date',
            field=models.DateTimeField(blank=True, help_text='Date order was issued', null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_pickup', 'Awaiting Pickup'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Return order status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shipment Date'),
        ),
        migrations.CreateModel(
            name='ReturnOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField()),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('original_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.purchaseorderlineitem')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.returnorder')),
            ],
        ),
    ]
