# Generated by Django 5.2 on 2025-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_returnorder_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer_reference',
            field=models.CharField(blank=True, help_text='Customer order reference code', max_length=64, null=True, verbose_name='Customer Reference '),
        ),
    ]
