services:
  web:
    # image: ubongpr7/inventory:latest
    image: nas415/crafterv5:latest
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:7701
      "
    volumes:
      - .:/app
    ports:
      - "7701:7701"

      