services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - inventory_network
    restart: unless-stopped

  web:
    image: ubongpr7/inventoryv2:latest
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - inventory_network
    restart: unless-stopped

  celery:
    image: ubongpr7/inventoryv2:latest
    env_file:
      - .env
    command: celery -A core worker --loglevel=info --pool=solo
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
    networks:
      - inventory_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  inventory_network:

