# Generated by Django 4.2.13 on 2024-05-30 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iso4217
import mainapps.inventory.helpers.field_validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company name')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('description', models.CharField(blank=True, help_text='Briefly describe the company', max_length=1000, null=True, verbose_name='Company description')),
                ('website', models.URLField(blank=True, help_text='Company website URL (optional)', verbose_name='Website')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Contact email address (optional)', max_length=254, null=True, verbose_name='Email')),
                ('link', models.URLField(blank=True, help_text='Link to external company information or profile', verbose_name='Link/Website')),
                ('currency', models.CharField(blank=True, choices=[(iso4217.Currency['afn'], 'afn'), (iso4217.Currency['eur'], 'eur'), (iso4217.Currency['all'], 'all'), (iso4217.Currency['dzd'], 'dzd'), (iso4217.Currency['usd'], 'usd'), (iso4217.Currency['aoa'], 'aoa'), (iso4217.Currency['xcd'], 'xcd'), (iso4217.Currency['ars'], 'ars'), (iso4217.Currency['amd'], 'amd'), (iso4217.Currency['awg'], 'awg'), (iso4217.Currency['aud'], 'aud'), (iso4217.Currency['azn'], 'azn'), (iso4217.Currency['bsd'], 'bsd'), (iso4217.Currency['bhd'], 'bhd'), (iso4217.Currency['bdt'], 'bdt'), (iso4217.Currency['bbd'], 'bbd'), (iso4217.Currency['byn'], 'byn'), (iso4217.Currency['bzd'], 'bzd'), (iso4217.Currency['xof'], 'xof'), (iso4217.Currency['bmd'], 'bmd'), (iso4217.Currency['inr'], 'inr'), (iso4217.Currency['btn'], 'btn'), (iso4217.Currency['bob'], 'bob'), (iso4217.Currency['bov'], 'bov'), (iso4217.Currency['bam'], 'bam'), (iso4217.Currency['bwp'], 'bwp'), (iso4217.Currency['nok'], 'nok'), (iso4217.Currency['brl'], 'brl'), (iso4217.Currency['bnd'], 'bnd'), (iso4217.Currency['bgn'], 'bgn'), (iso4217.Currency['bif'], 'bif'), (iso4217.Currency['cve'], 'cve'), (iso4217.Currency['khr'], 'khr'), (iso4217.Currency['xaf'], 'xaf'), (iso4217.Currency['cad'], 'cad'), (iso4217.Currency['kyd'], 'kyd'), (iso4217.Currency['clp'], 'clp'), (iso4217.Currency['clf'], 'clf'), (iso4217.Currency['cny'], 'cny'), (iso4217.Currency['cop'], 'cop'), (iso4217.Currency['cou'], 'cou'), (iso4217.Currency['kmf'], 'kmf'), (iso4217.Currency['cdf'], 'cdf'), (iso4217.Currency['nzd'], 'nzd'), (iso4217.Currency['crc'], 'crc'), (iso4217.Currency['hrk'], 'hrk'), (iso4217.Currency['cup'], 'cup'), (iso4217.Currency['cuc'], 'cuc'), (iso4217.Currency['ang'], 'ang'), (iso4217.Currency['czk'], 'czk'), (iso4217.Currency['dkk'], 'dkk'), (iso4217.Currency['djf'], 'djf'), (iso4217.Currency['dop'], 'dop'), (iso4217.Currency['egp'], 'egp'), (iso4217.Currency['svc'], 'svc'), (iso4217.Currency['ern'], 'ern'), (iso4217.Currency['szl'], 'szl'), (iso4217.Currency['etb'], 'etb'), (iso4217.Currency['fkp'], 'fkp'), (iso4217.Currency['fjd'], 'fjd'), (iso4217.Currency['xpf'], 'xpf'), (iso4217.Currency['gmd'], 'gmd'), (iso4217.Currency['gel'], 'gel'), (iso4217.Currency['ghs'], 'ghs'), (iso4217.Currency['gip'], 'gip'), (iso4217.Currency['gtq'], 'gtq'), (iso4217.Currency['gbp'], 'gbp'), (iso4217.Currency['gnf'], 'gnf'), (iso4217.Currency['gyd'], 'gyd'), (iso4217.Currency['htg'], 'htg'), (iso4217.Currency['hnl'], 'hnl'), (iso4217.Currency['hkd'], 'hkd'), (iso4217.Currency['huf'], 'huf'), (iso4217.Currency['isk'], 'isk'), (iso4217.Currency['idr'], 'idr'), (iso4217.Currency['xdr'], 'xdr'), (iso4217.Currency['irr'], 'irr'), (iso4217.Currency['iqd'], 'iqd'), (iso4217.Currency['ils'], 'ils'), (iso4217.Currency['jmd'], 'jmd'), (iso4217.Currency['jpy'], 'jpy'), (iso4217.Currency['jod'], 'jod'), (iso4217.Currency['kzt'], 'kzt'), (iso4217.Currency['kes'], 'kes'), (iso4217.Currency['kpw'], 'kpw'), (iso4217.Currency['krw'], 'krw'), (iso4217.Currency['kwd'], 'kwd'), (iso4217.Currency['kgs'], 'kgs'), (iso4217.Currency['lak'], 'lak'), (iso4217.Currency['lbp'], 'lbp'), (iso4217.Currency['lsl'], 'lsl'), (iso4217.Currency['zar'], 'zar'), (iso4217.Currency['lrd'], 'lrd'), (iso4217.Currency['lyd'], 'lyd'), (iso4217.Currency['chf'], 'chf'), (iso4217.Currency['mop'], 'mop'), (iso4217.Currency['mkd'], 'mkd'), (iso4217.Currency['mga'], 'mga'), (iso4217.Currency['mwk'], 'mwk'), (iso4217.Currency['myr'], 'myr'), (iso4217.Currency['mvr'], 'mvr'), (iso4217.Currency['mru'], 'mru'), (iso4217.Currency['mur'], 'mur'), (iso4217.Currency['xua'], 'xua'), (iso4217.Currency['mxn'], 'mxn'), (iso4217.Currency['mxv'], 'mxv'), (iso4217.Currency['mdl'], 'mdl'), (iso4217.Currency['mnt'], 'mnt'), (iso4217.Currency['mad'], 'mad'), (iso4217.Currency['mzn'], 'mzn'), (iso4217.Currency['mmk'], 'mmk'), (iso4217.Currency['nad'], 'nad'), (iso4217.Currency['npr'], 'npr'), (iso4217.Currency['nio'], 'nio'), (iso4217.Currency['ngn'], 'ngn'), (iso4217.Currency['omr'], 'omr'), (iso4217.Currency['pkr'], 'pkr'), (iso4217.Currency['pab'], 'pab'), (iso4217.Currency['pgk'], 'pgk'), (iso4217.Currency['pyg'], 'pyg'), (iso4217.Currency['pen'], 'pen'), (iso4217.Currency['php'], 'php'), (iso4217.Currency['pln'], 'pln'), (iso4217.Currency['qar'], 'qar'), (iso4217.Currency['ron'], 'ron'), (iso4217.Currency['rub'], 'rub'), (iso4217.Currency['rwf'], 'rwf'), (iso4217.Currency['shp'], 'shp'), (iso4217.Currency['wst'], 'wst'), (iso4217.Currency['stn'], 'stn'), (iso4217.Currency['sar'], 'sar'), (iso4217.Currency['rsd'], 'rsd'), (iso4217.Currency['scr'], 'scr'), (iso4217.Currency['sll'], 'sll'), (iso4217.Currency['sle'], 'sle'), (iso4217.Currency['sgd'], 'sgd'), (iso4217.Currency['xsu'], 'xsu'), (iso4217.Currency['sbd'], 'sbd'), (iso4217.Currency['sos'], 'sos'), (iso4217.Currency['ssp'], 'ssp'), (iso4217.Currency['lkr'], 'lkr'), (iso4217.Currency['sdg'], 'sdg'), (iso4217.Currency['srd'], 'srd'), (iso4217.Currency['sek'], 'sek'), (iso4217.Currency['che'], 'che'), (iso4217.Currency['chw'], 'chw'), (iso4217.Currency['syp'], 'syp'), (iso4217.Currency['twd'], 'twd'), (iso4217.Currency['tjs'], 'tjs'), (iso4217.Currency['tzs'], 'tzs'), (iso4217.Currency['thb'], 'thb'), (iso4217.Currency['top'], 'top'), (iso4217.Currency['ttd'], 'ttd'), (iso4217.Currency['tnd'], 'tnd'), (iso4217.Currency['try'], 'try'), (iso4217.Currency['tmt'], 'tmt'), (iso4217.Currency['ugx'], 'ugx'), (iso4217.Currency['uah'], 'uah'), (iso4217.Currency['aed'], 'aed'), (iso4217.Currency['usn'], 'usn'), (iso4217.Currency['uyu'], 'uyu'), (iso4217.Currency['uyi'], 'uyi'), (iso4217.Currency['uyw'], 'uyw'), (iso4217.Currency['uzs'], 'uzs'), (iso4217.Currency['vuv'], 'vuv'), (iso4217.Currency['ves'], 'ves'), (iso4217.Currency['ved'], 'ved'), (iso4217.Currency['vnd'], 'vnd'), (iso4217.Currency['yer'], 'yer'), (iso4217.Currency['zmw'], 'zmw'), (iso4217.Currency['zwl'], 'zwl'), (iso4217.Currency['xba'], 'xba'), (iso4217.Currency['xbb'], 'xbb'), (iso4217.Currency['xbc'], 'xbc'), (iso4217.Currency['xbd'], 'xbd'), (iso4217.Currency['xts'], 'xts'), (iso4217.Currency['xxx'], 'xxx'), (iso4217.Currency['xau'], 'xau'), (iso4217.Currency['xpd'], 'xpd'), (iso4217.Currency['xpt'], 'xpt'), (iso4217.Currency['xag'], 'xag')], default='USD', help_text='Set company default currency', max_length=12, validators=[mainapps.inventory.helpers.field_validators.validate_currency_code], verbose_name='Base Currency')),
                ('created_by', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.companyprofile')),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
