# Generated by Django 5.1.7 on 2025-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=20, verbose_name='Phone number'),
        ),
    ]
