# Generated by Django 5.1.7 on 2025-03-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="inventory_sequence",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
