# Generated by Django 4.2.13 on 2024-05-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_type_which_model'),
        ('management', '0002_alter_companyprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.ForeignKey(limit_choices_to={'which_model': 'industry'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.type'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.companyprofile'),
        ),
        migrations.CreateModel(
            name='PrescriptionFillingPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Policy name')),
                ('details', models.TextField(unique=True, verbose_name='Details of the policy')),
                ('effective_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_period', models.IntegerField(default=5, help_text='Prescription is valid before how many days')),
                ('quantitity_limit', models.IntegerField()),
                ('refills_allowed', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Policy name')),
                ('details', models.TextField(unique=True, verbose_name='Details of the policy')),
                ('effective_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_stock_level', models.IntegerField()),
                ('re_order_point', models.IntegerField()),
                ('re_order_quauntity', models.IntegerField()),
                ('recall_policy', models.CharField(choices=[('0', 'Remove from stock'), ('1', 'Notify customers'), ('3', 'Replace item'), ('4', 'Destroy item'), ('5', 'Repair item')], max_length=200)),
                ('expiration_policy', models.CharField(choices=[('0', 'Dispose of stock'), ('1', 'Return to manufacturer')], max_length=200)),
                ('automate_reorder', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
