# Generated by Django 5.1.7 on 2025-03-29 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_companyprofile_phone'),
        ('permit', '0005_alter_customuserpermission_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrole',
            name='policies',
        ),
        migrations.RemoveField(
            model_name='staffpolicy',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='staffpolicy',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='policies',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='users',
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='permit.customuserpermission'),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolse_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='permit.customuserpermission'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffroleassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffroleassignment',
            name='assigned_by',
            field=models.ForeignKey(help_text='User who assigned the role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RolePolicyAssignment',
        ),
        migrations.DeleteModel(
            name='StaffPolicy',
        ),
    ]
