# Generated by Django 4.2.13 on 2024-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_companyprofile_industry_alter_staff_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryPolicy',
        ),
    ]
