# Generated by Django 5.1.7 on 2025-03-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_staffrole_policies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolse_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffroleassignment',
            name='assigned_by',
            field=models.ForeignKey(editable=False, help_text='User who assigned the role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
