# Generated by Django 5.1.7 on 2025-03-30 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_staffrole_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='staff_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
