# Generated by Django 5.1.7 on 2025-03-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_staffgroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.staffrole'),
        ),
    ]
