# Generated by Django 4.2.13 on 2024-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_staffuser_remove_companyprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='unique_id',
            field=models.CharField(default='146686676804723', max_length=15, unique=True),
        ),
    ]
