# Generated by Django 4.2.13 on 2024-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_companyprofile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='is_main',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='unique_id',
            field=models.CharField(default='155331083343636', max_length=15, unique=True),
        ),
    ]
