# Generated by Django 4.2.13 on 2024-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_companyprofile_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffuser',
            old_name='company',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='unique_id',
            field=models.CharField(default='293096986779903', editable=False, max_length=15, unique=True),
        ),
    ]
