# Generated by Django 4.2.13 on 2024-06-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_companyprofile_unique_id_delete_staffuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='unique_id',
            field=models.CharField(default='120928680477877', editable=False, max_length=15, unique=True),
        ),
    ]
