# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the linked object.', verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(help_text='The content type of the linked object.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It must be unique', max_length=200, verbose_name='Type')),
                ('which_model', models.CharField(choices=[('inventory', 'Inventory'), ('stock_item', 'Stock item'), ('company', 'Company'), ('policy', 'Policy'), ('industry', 'Industry')], max_length=30)),
                ('slug', models.SlugField(editable=False, max_length=230)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.typeof')),
            ],
            options={
                'verbose_name_plural': 'Types of Instances',
                'constraints': [models.UniqueConstraint(fields=('name', 'which_model'), name='unique_type_name_which_model')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_type', models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('length', 'Length'), ('piece', 'Piece'), ('time', 'Time'), ('custom', 'Custom')], default='custom', help_text='Type of measurement this unit belongs to', max_length=50, verbose_name='Dimension Category')),
                ('name', models.CharField(help_text='Full name of the unit (e.g., Kilogram)', max_length=255, verbose_name='Unit Name')),
                ('abbreviated_name', models.CharField(help_text='Standard short form (e.g., kg, L, m)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_abbreviation', message='Abbreviation can only contain letters', regex='^[A-Za-z]+$')], verbose_name='Abbreviation')),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=1.0, help_text='Conversion factor to base unit', max_digits=30)),
                ('base_unit', models.ForeignKey(blank=True, help_text='Reference to base unit for conversions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.unit', verbose_name='Base Unit')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['dimension_type', 'name'], name='common_unit_dimensi_534886_idx'), models.Index(fields=['abbreviated_name'], name='common_unit_abbrevi_187618_idx')],
                'constraints': [models.UniqueConstraint(fields=('dimension_type', 'name'), name='unique_unit_per_dimension'), models.UniqueConstraint(fields=('abbreviated_name', 'dimension_type'), name='unique_abbreviation_per_dimension')],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.attribute')),
            ],
            options={
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
