# Generated by Django 5.1.7 on 2025-03-12 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="attribute",
        ),
        migrations.AddField(
            model_name="unit",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to base unit for conversions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.unit",
                verbose_name="Base Unit",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="conversion_factor",
            field=models.DecimalField(
                decimal_places=6,
                default=1.0,
                help_text="Conversion factor to base unit",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="dimension_type",
            field=models.CharField(
                choices=[
                    ("mass", "Mass"),
                    ("volume", "Volume"),
                    ("length", "Length"),
                    ("piece", "Piece"),
                    ("time", "Time"),
                    ("custom", "Custom"),
                ],
                default="custom",
                help_text="Type of measurement this unit belongs to",
                max_length=50,
                verbose_name="Dimension Category",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="abbreviated_name",
            field=models.CharField(
                help_text="Standard short form (e.g., kg, L, m)",
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_abbreviation",
                        message="Abbreviation can only contain letters",
                        regex="^[A-Za-z]+$",
                    )
                ],
                verbose_name="Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                help_text="Full name of the unit (e.g., Kilogram)",
                max_length=255,
                verbose_name="Unit Name",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["dimension_type", "name"], name="common_unit_dimensi_534886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["abbreviated_name"], name="common_unit_abbrevi_187618_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("dimension_type", "name"), name="unique_unit_per_dimension"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("abbreviated_name", "dimension_type"),
                name="unique_abbreviation_per_dimension",
            ),
        ),
    ]
