# Generated by Django 5.2 on 2025-04-19 04:27

import django.db.models.deletion
import mainapps.common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=mainapps.common.models.attachment_upload_path)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOC', 'Document'), ('OTHER', 'Other')], max_length=20)),
                ('purpose', models.CharField(choices=[('MAIN_IMAGE', 'Main Product Image'), ('GALLERY', 'Gallery Image'), ('MANUAL', 'Product Manual'), ('SPEC', 'Specification Sheet')], default='GALLERY', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-is_primary', 'uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_atta_content_060193_idx')],
            },
        ),
    ]
