# Generated by Django 5.1.7 on 2025-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_remove_unit_attribute_unit_base_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="conversion_factor",
            field=models.DecimalField(
                decimal_places=8,
                default=1.0,
                help_text="Conversion factor to base unit",
                max_digits=30,
            ),
        ),
    ]
