# Generated by Django 5.1.7 on 2025-03-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_unit_conversion_factor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typeof",
            options={"verbose_name_plural": "Types of Instances"},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["id"]},
        ),
    ]
