# Generated by Django 5.0.4 on 2024-05-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_attributestore_attributes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('attribute', 'value')},
        ),
    ]
