# Generated by Django 4.2.13 on 2024-06-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_companyprofile_unique_id'),
        ('inventory', '0009_inventory_automate_reorder_and_more'),
        ('common', '0007_alter_type_which_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TypeOf',
        ),
    ]
