# Generated by Django 4.2.13 on 2024-06-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_typeof_options_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
    ]
