# Generated by Django 4.2.13 on 2024-06-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_country_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
