# Generated by Django 4.2.13 on 2024-06-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='abbreviated_name',
            field=models.CharField(blank=True, help_text='What is the short form of the unit', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='attribute',
            field=models.ForeignKey(help_text='What attribute does the unit measure?', on_delete=django.db.models.deletion.CASCADE, to='common.attribute'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Unit name'),
        ),
    ]
