# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.core.validators
import django.db.models.deletion
import mainapps.common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, validators=[mainapps.common.validators.validate_postal_code], verbose_name='Postal code')),
                ('title', models.CharField(help_text='Title describing the address entry', max_length=100, verbose_name='Address title')),
                ('primary', models.BooleanField(default=False, help_text='Set as primary or main address', verbose_name='Primary address')),
                ('shipping_notes', models.CharField(blank=True, help_text='Notes for shipping courier', max_length=100, verbose_name='Courier shipping notes')),
                ('internal_shipping_notes', models.CharField(blank=True, help_text='Shipping notes for internal use', max_length=100, verbose_name='Internal shipping notes')),
                ('link', models.URLField(blank=True, help_text='Link to address information (external)', null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('role', models.CharField(blank=True, help_text='Contact person role in company', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_alphanumeric', message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9]*$')], verbose_name='Role')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
                ('description', models.CharField(blank=True, help_text='Briefly describe the company', max_length=1000, null=True, verbose_name='Company description')),
                ('website', models.URLField(blank=True, help_text='Company website URL (optional)', null=True, verbose_name='Website')),
                ('short_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Contact email address (optional)', max_length=254, null=True, verbose_name='Email')),
                ('link', models.URLField(blank=True, help_text='Link to external company information or profile', verbose_name='Link/Website')),
                ('is_customer', models.BooleanField(default=False, help_text='Do you sell items to this company?', verbose_name='is customer')),
                ('is_supplier', models.BooleanField(default=False, help_text='Do you purchase items from this company?', verbose_name='Is supplier')),
                ('is_manufacturer', models.BooleanField(default=False, help_text='Does this company manufacture parts?', verbose_name='is manufacturer')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
