# Generated by Django 4.2.13 on 2024-05-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the company', max_length=1000, null=True, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Do you purchase items from this company?', verbose_name='Is supplier'),
        ),
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.URLField(blank=True, help_text='Link to external company information or profile', verbose_name='Link/Website'),
        ),
    ]
