# Generated by Django 5.1.7 on 2025-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
    ]
