# Generated by Django 5.1.7 on 2025-03-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_currency'),
        ('company', '0003_company_short_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
    ]
