# Generated by Django 4.2.13 on 2024-05-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_created_by_alter_company_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, help_text='This field is optional. Please enter your street number.', max_length=200, null=True, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, help_text='Street name', max_length=50, verbose_name='Street'),
        ),
    ]
