# Generated by Django 5.1.7 on 2025-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_currency'),
        ('management', '0002_companyprofile_inventory_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', related_query_name='company', to='management.companyprofile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL (optional)', null=True, verbose_name='Website'),
        ),
    ]
