# Generated by Django 4.2.13 on 2024-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_is_owner_address_street_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_patiant',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, help_text='Briefly describe the company', max_length=1000, null=True, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address (optional)', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL (optional)', verbose_name='Website'),
        ),
    ]
