# Generated by Django 4.2.13 on 2024-05-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('company', '0005_remove_company_contact_remove_company_is_patiant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_name',
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', related_query_name='company', to='management.companyprofile'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_company_name_profile'),
        ),
    ]
