# Generated by Django 4.2.13 on 2024-06-01 12:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Location country', max_length=2, null=True, verbose_name='Country'),
        ),
    ]
