# Generated by Django 4.2.13 on 2024-06-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(help_text='Pick the state or region', max_length=50, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Town and city', max_length=50, null=True, verbose_name='Town, City,'),
        ),
    ]
