# Generated by Django 4.2.13 on 2024-06-03 10:55

from django.db import migrations, models
import mainapps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_address_region_alter_address_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, validators=[mainapps.common.validators.validate_postal_code], verbose_name='Postal code')),
                ('title', models.CharField(help_text='Title describing the address entry', max_length=100, verbose_name='Address title')),
                ('primary', models.BooleanField(default=False, help_text='Set as primary or main address', verbose_name='Primary address')),
                ('shipping_notes', models.CharField(blank=True, help_text='Notes for shipping courier', max_length=100, verbose_name='Courier shipping notes')),
                ('internal_shipping_notes', models.CharField(blank=True, help_text='Shipping notes for internal use', max_length=100, verbose_name='Internal shipping notes')),
                ('link', models.URLField(blank=True, help_text='Link to address information (external)', null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='company',
        ),
    ]
