# Generated by Django 4.2.13 on 2024-06-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('company', '0011_companyaddress_remove_address_company'),
        ('orders', '0004_alter_purchaseorder_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(help_text='Select company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region/State'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='sub_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='Sub region/LGA'),
        ),
    ]
