# Generated by Django 5.0.4 on 2024-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'permissions': (('code', 'message'), ('can_copy_code', 'Can copy code'), ('can_share_code', 'Can share code'))},
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('user', 'User'), ('customer', 'Customer')], default='user', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
