# Generated by Django 5.0.4 on 2024-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_apt_number_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_name',
            field=models.CharField(blank=True, help_text='Enter you Home Address.', max_length=200, null=True, verbose_name='Street Name'),
        ),
    ]
