# Generated by Django 4.2.13 on 2024-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
