# Generated by Django 4.2.13 on 2024-06-01 12:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Nigeria', max_length=50, null=True),
        ),
    ]
