# Generated by Django 4.2.13 on 2024-06-03 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0012_alter_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, validators=[mainapps.common.validators.validate_postal_code], verbose_name='Postal code')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City/Town')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region/State')),
                ('resident', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence', to=settings.AUTH_USER_MODEL)),
                ('sub_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='Sub region/LGA')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
