# Generated by Django 4.2.13 on 2024-06-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_residentialaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentialaddress',
            old_name='sub_region',
            new_name='subregion',
        ),
    ]
