# Generated by Django 4.2.13 on 2024-06-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_is_main_alter_user_is_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_main',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
