# Generated by Django 5.2 on 2025-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='packaging',
            field=models.CharField(blank=True, help_text='Description of how the StockItem is packaged (e.g. "reel", "loose", "tape" etc)', max_length=100, null=True, verbose_name='Packaging'),
        ),
    ]
