# Generated by Django 5.1.7 on 2025-03-13 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventory_alert_threshold_and_more"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocklocationtype",
            name="icon",
        ),
        migrations.AlterField(
            model_name="stockitemtracking",
            name="tracking_type",
            field=models.IntegerField(
                choices=[
                    (10, "Items received from supplier"),
                    (11, "Received against purchase order"),
                    (12, "Items returned from customer"),
                    (20, "Items shipped to customer"),
                    (21, "Shipped against sales order"),
                    (22, "Used in manufacturing process"),
                    (30, "Manual quantity adjustment"),
                    (31, "Moved between locations"),
                    (32, "Split from parent stock"),
                    (33, "Merged with parent stock"),
                    (40, "Placed in quarantine"),
                    (41, "Quality inspection performed"),
                    (42, "Rejected during inspection"),
                    (50, "Manual stock count performed"),
                    (51, "Automatic restock triggered"),
                    (52, "Near expiry date notification"),
                    (60, "Stock status updated"),
                    (61, "Damage reported on item"),
                    (0, "Other Uncategorized tracking event"),
                ],
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="stockitemtracking",
            index=models.Index(
                fields=["date", "item"], name="stock_stock_date_0f3229_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitemtracking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tracking_type__in",
                        [
                            10,
                            11,
                            12,
                            20,
                            21,
                            22,
                            30,
                            31,
                            32,
                            33,
                            40,
                            41,
                            42,
                            50,
                            51,
                            52,
                            60,
                            61,
                            0,
                        ],
                    )
                ),
                name="valid_tracking_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                fields=("inventory", "name"), name="unique_location_name_per_inventory"
            ),
        ),
    ]
