# Generated by Django 5.1.7 on 2025-03-21 00:43

import mainapps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stocklocationtype_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock keeping unit for this stock item', max_length=100, null=True, validators=[mainapps.utils.validators.validate_serial_number], verbose_name='Stock keeping unit'),
        ),
    ]
