# Generated by Django 5.2 on 2025-04-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_staffroleassignment_role'),
        ('stock', '0003_stockitem_created_at_stockitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stocklocation',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='stocklocation',
            name='unique_location_name_per_inventory',
        ),
        migrations.RemoveField(
            model_name='stocklocation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stocklocation',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='stocklocation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='name',
            field=models.CharField(help_text='Name of the stock item', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profile for this stock location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='management.companyprofile', verbose_name='Profile'),
        ),
    ]
