# Generated by Django 5.2 on 2025-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stocklocation_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocationtype',
            options={'ordering': ['id'], 'verbose_name': 'Stock Location Type', 'verbose_name_plural': 'Stock Location Types'},
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Unique location identifier (auto-generated)', max_length=100, null=True, unique=True, verbose_name='Location Code'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='description',
            field=models.TextField(blank=True, help_text='Longer form description of the stock location (optional)', null=True, verbose_name='Description'),
        ),
    ]
