# Generated by Django 5.2 on 2025-04-06 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stocklocationtype_options_stocklocation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date that this stock location was created', verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date that this stock location was last updated', verbose_name='Updated at'),
        ),
    ]
