# Generated by Django 4.2.13 on 2024-06-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockcategory_id_alter_stockitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='StockCategory',
        ),
    ]
