# Generated by Django 5.2 on 2025-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stocklocation_created_at_stocklocation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='note',
            field=models.TextField(blank=True, help_text='Extra notes field', null=True, verbose_name='Notes'),
        ),
    ]
