# Generated by Django 4.2.13 on 2024-06-14 21:05

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockitemtracking_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The location this falls under eg if this is a sub location in a bigger location like warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock.stocklocation', verbose_name='Super Location'),
        ),
    ]
