# Generated by Django 5.2 on 2025-04-06 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('inventory', '0004_inventorypricing_created_at_and_more'),
        ('orders', '0005_salesordershipment_created_at_and_more'),
        ('stock', '0008_rename_note_stockitem_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name', 'serial'], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['name', 'serial'], name='stock_stock_name_e9cfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['location'], name='stock_stock_locatio_202e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['parent'], name='stock_stock_parent__1f9fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['batch'], name='stock_stock_batch_367136_idx'),
        ),
    ]
