# Generated by Django 4.2.13 on 2024-06-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stocklocation_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
