# Generated by Django 5.2 on 2025-04-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='batch',
            field=models.CharField(blank=True, help_text='Batch code for this stock item', max_length=100, null=True, verbose_name='Batch Code'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='serial',
            field=models.CharField(blank=True, help_text='Unique serial number for this StockItem', max_length=100, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock keeping unit for this stock item', max_length=100, null=True, verbose_name='Stock keeping unit'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('attention_needed', 'Attention needed'), ('damaged', 'Damaged'), ('destroyed', 'Destroyed'), ('rejected', 'Rejected'), ('lost', 'Lost'), ('quarantined', 'Quarantined'), ('returned', 'Returned')], default='ok', help_text='Status of this StockItem ', max_length=50, verbose_name='Status'),
        ),
    ]
