# Generated by Django 5.2 on 2025-04-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('stock', '0014_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Product variant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='product.productvariant', verbose_name='Product Variant'),
        ),
    ]
