# Generated by Django 5.2 on 2025-04-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('inventory', '0006_inventorytransaction_unit_price'),
        ('orders', '0015_alter_salesorder_customer_reference'),
        ('product', '0002_productvariant_variant_number'),
        ('stock', '0015_stockitem_product_stockitem_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_stock_name_e9cfb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_stock_parent__1f9fcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_stock_batch_367136_idx',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Product variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='product.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['variant'], name='stock_stock_variant_1791bf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['batch', 'serial'], name='stock_stock_batch_14da60_idx'),
        ),
    ]
