# Generated by Django 5.2 on 2025-04-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_remove_stockitem_stock_stock_name_e9cfb2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='stock_item',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
