# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('inventory', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='profile',
            field=models.ForeignKey(help_text='Organization responsible for this inventory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='management.companyprofile', verbose_name='Owning Organization'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Standard measurement system for stock items (e.g., pieces, kg)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='common.unit', verbose_name='Measurement Unit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified policies', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
    ]
