# Generated by Django 5.1.7 on 2025-03-11 07:23

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("inventory", "0001_initial"),
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="profile",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventories",
                related_query_name="inventory",
                to="management.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Set unit for items in this inventory e.g pieces,cm,m...",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventories",
                to="common.unit",
                verbose_name="Unit of measurement",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Parent  to which this category falls",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="inventory.inventorycategory",
                verbose_name="Parent category",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_categories",
                related_query_name="inventory_category",
                to="management.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventories",
                to="inventory.inventorycategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycategory",
            constraint=models.UniqueConstraint(
                fields=("name", "profile"), name="unique_name_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("name", "profile"), name="unique_inventory_name_profile"
            ),
        ),
    ]
