# Generated by Django 4.2.13 on 2024-05-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_linking_models', '0003_category'),
        ('company', '0002_company_created_by_company_is_owner_and_more'),
        ('inventory', '0002_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='content_type_linking_models.category'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, limit_choices_to={'is_owner': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
