# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('inventory', '0002_initial'),
        ('management', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='default_location',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Default location for parts in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='stock.stocklocation', verbose_name='Default Location'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent  to which this category falls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventorycategory', verbose_name='Parent category'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', related_query_name='inventory_category', to='management.companyprofile'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Hierarchical grouping for inventory items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventory.inventorycategory', verbose_name='Classification Category'),
        ),
        migrations.AddField(
            model_name='inventorypricing',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AddField(
            model_name='inventorypricing',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_name_profile'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('external_system_id', 'profile'), name='unique_inventory_external_system_id_profile'),
        ),
    ]
