# Generated by Django 4.2.13 on 2024-05-25 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_company_created_by_company_is_owner_and_more'),
        ('inventory', '0003_inventory_category_inventory_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_owner': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL),
        ),
    ]
