# Generated by Django 5.1.7 on 2025-03-13 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_typeof_options_alter_unit_options"),
        ("inventory", "0003_inventory_alert_threshold_and_more"),
        ("management", "0002_companyprofile_inventory_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventory",
            name="unique_inventory_name_profile",
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("external_system_id", "profile"),
                name="unique_inventory_external_system_id_profile",
            ),
        ),
    ]
