# Generated by Django 5.2 on 2025-04-08 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorypricing_created_at_and_more'),
        ('management', '0006_alter_staffroleassignment_role'),
        ('stock', '0013_alter_sale_total_alter_saleitem_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('transaction_type', models.CharField(choices=[('PO_RECEIVE', 'Purchase Order Receipt'), ('PO_COMPLETE', 'Purchase Order Completion'), ('ADJUSTMENT', 'Inventory Adjustment'), ('SALE', 'Customer Sale'), ('RETURN', 'Inventory Return'), ('LOSS', 'Inventory Loss')], default='PO_COMPLETE', max_length=20)),
                ('reference', models.CharField(help_text='Associated document number (PO, SO, etc)', max_length=64)),
                ('notes', models.TextField(blank=True, help_text='Additional transaction details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.stockitem')),
                ('profile', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='management.companyprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
