# Generated by Django 5.1.7 on 2025-03-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_inventory_unique_inventory_name_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="i_type",
            new_name="inventory_type",
        ),
    ]
