# Generated by Django 5.2 on 2025-04-08 16:53

import django.core.validators
import mainapps.common.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_price',
            field=mainapps.common.custom_fields.MoneyField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
