# Generated by Django 4.2.13 on 2024-05-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorycategory_alter_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='company',
        ),
    ]
