# Generated by Django 4.2.13 on 2024-05-30 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_type_type_unique_type_name_which_model'),
        ('management', '0001_initial'),
        ('inventory', '0006_remove_inventory_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='permissionlog',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='permissionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='inventory',
            name='i_type',
            field=models.ForeignKey(limit_choices_to={'which_model': 'inventory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', related_query_name='inventory', to='management.companyprofile'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_categories', related_query_name='inventory_category', to='management.companyprofile'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_inventory_name_profile'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_name_profile'),
        ),
        migrations.DeleteModel(
            name='PermissionLog',
        ),
    ]
