# Generated by Django 5.2 on 2025-04-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorytransaction_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
    ]
