# Generated by Django 4.2.13 on 2024-05-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_type_which_model'),
        ('inventory', '0008_alter_inventory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='automate_reorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiration_policy',
            field=models.CharField(choices=[('0', 'Dispose of stock'), ('1', 'Return to manufacturer')], default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimum_stock_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='re_order_point',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='re_order_quauntity',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='recall_policy',
            field=models.CharField(choices=[('0', 'Remove from stock'), ('1', 'Notify customers'), ('3', 'Replace item'), ('4', 'Destroy item'), ('5', 'Repair item')], default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Set unit for items in this inventory e.g pieces,cm,m...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='common.unit', verbose_name='Global'),
        ),
    ]
