# Generated by Django 4.2.13 on 2024-06-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_companyprofile_unique_id'),
        ('inventory', '0010_alter_inventory_automate_reorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_categories', related_query_name='inventory_category', to='management.companyprofile'),
        ),
    ]
