# Generated by Django 5.2 on 2025-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
