# Generated by Django 5.2 on 2025-04-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('product', '0002_productvariant_variant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.unit'),
        ),
    ]
