# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Permission Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permit.permissioncategory')),
            ],
            options={
                'ordering': ['category', 'codename'],
                'indexes': [models.Index(fields=['codename'], name='permit_cust_codenam_3d728b_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'codename'), name='unique_permission_per_category')],
            },
        ),
    ]
