# Generated by Django 5.0.4 on 2024-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_generate_report', 'Can generate report'), ('can_download_report', 'Can download report'), ('can_confirm_sales_order', 'Can confirm sales order'), ('can_confirm_purchase_order', 'Can confirm purchase order')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
