# Generated by Django 5.1.7 on 2025-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_alter_customuserpermission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserpermission',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed explanation of permission scope', null=True),
        ),
    ]
